/**
 * Source Priorities and Monitoring Configuration
 * Defines monitoring frequency and priority levels for all data sources
 */

export interface SourcePriority {
  priority: 'high' | 'medium' | 'low';
  monitoring: 'daily' | 'weekly' | 'monthly';
  category: string;
  enabled: boolean;
  retryAttempts: number;
  timeout: number;
  // Enhanced monitoring fields
  healthStatus: 'healthy' | 'degraded' | 'down' | 'unknown';
  lastChecked: Date | null;
  successRate: number;
  averageResponseTime: number;
  errorCount: number;
  lastError: string | null;
  // Rate limiting
  rateLimit: {
    requests: number;
    window: number; // in milliseconds
  };
  // Robots.txt compliance
  robotsTxt: string;
  respectRobotsTxt: boolean;
}

export interface SourceConfig {
  [sourceId: string]: SourcePriority;
}

// Helper function to create complete SourcePriority objects (unused - kept for future reference)
// function createSourcePriority(partial: Partial<SourcePriority>): SourcePriority {
//   return {
//     priority: partial.priority || 'medium',
//     monitoring: partial.monitoring || 'weekly',
//     category: partial.category || 'general',
//     enabled: partial.enabled ?? true,
//     retryAttempts: partial.retryAttempts || 3,
//     timeout: partial.timeout || 30000,
//     healthStatus: 'unknown',
//     lastChecked: null,
//     successRate: 0,
//     averageResponseTime: 0,
//     errorCount: 0,
//     lastError: null,
//     rateLimit: {
//       requests: 10,
//       window: 60000 // 1 minute
//     },
//     robotsTxt: '',
//     respectRobotsTxt: true,
//     ...partial
//   };
// }

// Health monitoring class
export class SourceHealthMonitor {
  private static instance: SourceHealthMonitor;
  private healthData: Map<string, SourcePriority> = new Map();

  static getInstance(): SourceHealthMonitor {
    if (!SourceHealthMonitor.instance) {
      SourceHealthMonitor.instance = new SourceHealthMonitor();
    }
    return SourceHealthMonitor.instance;
  }

  updateHealthStatus(sourceId: string, status: 'healthy' | 'degraded' | 'down', responseTime?: number, error?: string): void {
    const source = SOURCE_PRIORITIES[sourceId];
    if (!source) return;

    const now = new Date();
    const updatedSource = {
      ...source,
      healthStatus: status,
      lastChecked: now,
      averageResponseTime: responseTime ? (source.averageResponseTime + responseTime) / 2 : source.averageResponseTime,
      errorCount: error ? source.errorCount + 1 : source.errorCount,
      lastError: error || source.lastError,
      successRate: status === 'healthy' ? Math.min(100, source.successRate + 1) : Math.max(0, source.successRate - 5)
    };

    this.healthData.set(sourceId, updatedSource);
    SOURCE_PRIORITIES[sourceId] = updatedSource;
  }

  getHealthStatus(sourceId: string): SourcePriority | null {
    return this.healthData.get(sourceId) || SOURCE_PRIORITIES[sourceId] || null;
  }

  getAllHealthStatuses(): SourcePriority[] {
    return Array.from(this.healthData.values());
  }

  getUnhealthySources(): SourcePriority[] {
    return this.getAllHealthStatuses().filter(source => 
      source.healthStatus === 'down' || source.healthStatus === 'degraded'
    );
  }

  getSourcesNeedingCheck(): string[] {
    const now = new Date();
    return Object.keys(SOURCE_PRIORITIES).filter(sourceId => {
      const source = SOURCE_PRIORITIES[sourceId];
      if (!source.enabled) return false;
      
      const lastChecked = source.lastChecked;
      if (!lastChecked) return true;
      
      const timeSinceLastCheck = now.getTime() - lastChecked.getTime();
      const monitoringInterval = this.getMonitoringInterval(source.monitoring);
      
      return timeSinceLastCheck > monitoringInterval;
    });
  }

  private getMonitoringInterval(monitoring: 'daily' | 'weekly' | 'monthly'): number {
    switch (monitoring) {
      case 'daily': return 24 * 60 * 60 * 1000; // 24 hours
      case 'weekly': return 7 * 24 * 60 * 60 * 1000; // 7 days
      case 'monthly': return 30 * 24 * 60 * 60 * 1000; // 30 days
      default: return 24 * 60 * 60 * 1000;
    }
  }
}

// Source priorities and monitoring configuration
export const SOURCE_PRIORITIES: SourceConfig = {
  // HIGH PRIORITY - Daily monitoring (50 sources)
  'aws_at': {
    priority: 'high',
    monitoring: 'daily',
    category: 'austrian_grants',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: 'https://aws.at/robots.txt',
    respectRobotsTxt: true
  },
  'ffg_at': {
    priority: 'high',
    monitoring: 'daily',
    category: 'research_grants',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eic_europa': {
    priority: 'high',
    monitoring: 'daily',
    category: 'eu_programs',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'horizon_europe': {
    priority: 'high',
    monitoring: 'daily',
    category: 'eu_programs',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'wko_at': {
    priority: 'high',
    monitoring: 'daily',
    category: 'business_grants',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'ams_at': {
    priority: 'high',
    monitoring: 'daily',
    category: 'employment',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'vba_at': {
    priority: 'high',
    monitoring: 'daily',
    category: 'regional_grants',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'oesb_at': {
    priority: 'high',
    monitoring: 'daily',
    category: 'consulting',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'raiffeisen_at': {
    priority: 'high',
    monitoring: 'daily',
    category: 'banking',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'erste_at': {
    priority: 'high',
    monitoring: 'daily',
    category: 'banking',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'unicredit_at': {
    priority: 'high',
    monitoring: 'daily',
    category: 'banking',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'bawag_at': {
    priority: 'high',
    monitoring: 'daily',
    category: 'banking',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'volksbank_at': {
    priority: 'high',
    monitoring: 'daily',
    category: 'banking',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eif_europa': {
    priority: 'high',
    monitoring: 'daily',
    category: 'eu_programs',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_digital': {
    priority: 'high',
    monitoring: 'daily',
    category: 'eu_programs',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_health': {
    priority: 'high',
    monitoring: 'daily',
    category: 'health',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_urban_mobility': {
    priority: 'high',
    monitoring: 'daily',
    category: 'mobility',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_food': {
    priority: 'high',
    monitoring: 'daily',
    category: 'food',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_manufacturing': {
    priority: 'high',
    monitoring: 'daily',
    category: 'manufacturing',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_raw_materials': {
    priority: 'high',
    monitoring: 'daily',
    category: 'materials',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_climate': {
    priority: 'high',
    monitoring: 'daily',
    category: 'climate',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_culture_creativity': {
    priority: 'high',
    monitoring: 'daily',
    category: 'culture',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_energy': {
    priority: 'high',
    monitoring: 'daily',
    category: 'energy',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_water': {
    priority: 'high',
    monitoring: 'daily',
    category: 'water',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_ai': {
    priority: 'high',
    monitoring: 'daily',
    category: 'ai',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_blockchain': {
    priority: 'high',
    monitoring: 'daily',
    category: 'blockchain',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_cybersecurity': {
    priority: 'high',
    monitoring: 'daily',
    category: 'cybersecurity',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_quantum': {
    priority: 'high',
    monitoring: 'daily',
    category: 'quantum',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_space': {
    priority: 'high',
    monitoring: 'daily',
    category: 'space',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_robotics': {
    priority: 'high',
    monitoring: 'daily',
    category: 'robotics',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_biotech': {
    priority: 'high',
    monitoring: 'daily',
    category: 'biotech',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_medtech': {
    priority: 'high',
    monitoring: 'daily',
    category: 'medtech',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_fintech': {
    priority: 'high',
    monitoring: 'daily',
    category: 'fintech',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_edtech': {
    priority: 'high',
    monitoring: 'daily',
    category: 'edtech',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_agritech': {
    priority: 'high',
    monitoring: 'daily',
    category: 'agritech',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_cleantech': {
    priority: 'high',
    monitoring: 'daily',
    category: 'cleantech',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_greentech': {
    priority: 'high',
    monitoring: 'daily',
    category: 'greentech',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_smart_cities': {
    priority: 'high',
    monitoring: 'daily',
    category: 'smart_cities',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_digital_health': {
    priority: 'high',
    monitoring: 'daily',
    category: 'digital_health',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_industry_4_0': {
    priority: 'high',
    monitoring: 'daily',
    category: 'industry_4_0',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_circular_economy': {
    priority: 'high',
    monitoring: 'daily',
    category: 'circular_economy',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_sustainable_energy': {
    priority: 'high',
    monitoring: 'daily',
    category: 'sustainable_energy',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_blue_economy': {
    priority: 'high',
    monitoring: 'daily',
    category: 'blue_economy',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_ocean_tech': {
    priority: 'high',
    monitoring: 'daily',
    category: 'ocean_tech',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_forest_tech': {
    priority: 'high',
    monitoring: 'daily',
    category: 'forest_tech',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_arctic_tech': {
    priority: 'high',
    monitoring: 'daily',
    category: 'arctic_tech',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_urban_tech': {
    priority: 'high',
    monitoring: 'daily',
    category: 'urban_tech',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_rural_tech': {
    priority: 'high',
    monitoring: 'daily',
    category: 'rural_tech',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_mountain_tech': {
    priority: 'high',
    monitoring: 'daily',
    category: 'mountain_tech',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_desert_tech': {
    priority: 'high',
    monitoring: 'daily',
    category: 'desert_tech',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_tropical_tech': {
    priority: 'high',
    monitoring: 'daily',
    category: 'tropical_tech',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_polar_tech': {
    priority: 'high',
    monitoring: 'daily',
    category: 'polar_tech',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_equatorial_tech': {
    priority: 'high',
    monitoring: 'daily',
    category: 'equatorial_tech',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_temperate_tech': {
    priority: 'high',
    monitoring: 'daily',
    category: 'temperate_tech',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_continental_tech': {
    priority: 'high',
    monitoring: 'daily',
    category: 'continental_tech',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_maritime_tech': {
    priority: 'high',
    monitoring: 'daily',
    category: 'maritime_tech',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_aerospace_tech': {
    priority: 'high',
    monitoring: 'daily',
    category: 'aerospace_tech',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_automotive_tech': {
    priority: 'high',
    monitoring: 'daily',
    category: 'automotive_tech',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_railway_tech': {
    priority: 'high',
    monitoring: 'daily',
    category: 'railway_tech',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_aviation_tech': {
    priority: 'high',
    monitoring: 'daily',
    category: 'aviation_tech',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_shipping_tech': {
    priority: 'high',
    monitoring: 'daily',
    category: 'shipping_tech',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_logistics_tech': {
    priority: 'high',
    monitoring: 'daily',
    category: 'logistics_tech',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_supply_chain_tech': {
    priority: 'high',
    monitoring: 'daily',
    category: 'supply_chain_tech',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_warehouse_tech': {
    priority: 'high',
    monitoring: 'daily',
    category: 'warehouse_tech',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_distribution_tech': {
    priority: 'high',
    monitoring: 'daily',
    category: 'distribution_tech',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_retail_tech': {
    priority: 'high',
    monitoring: 'daily',
    category: 'retail_tech',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_ecommerce_tech': {
    priority: 'high',
    monitoring: 'daily',
    category: 'ecommerce_tech',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_marketplace_tech': {
    priority: 'high',
    monitoring: 'daily',
    category: 'marketplace_tech',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_platform_tech': {
    priority: 'high',
    monitoring: 'daily',
    category: 'platform_tech',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_saas_tech': {
    priority: 'high',
    monitoring: 'daily',
    category: 'saas_tech',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_paas_tech': {
    priority: 'high',
    monitoring: 'daily',
    category: 'paas_tech',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_iaas_tech': {
    priority: 'high',
    monitoring: 'daily',
    category: 'iaas_tech',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_cloud_tech': {
    priority: 'high',
    monitoring: 'daily',
    category: 'cloud_tech',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_edge_tech': {
    priority: 'high',
    monitoring: 'daily',
    category: 'edge_tech',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_iot_tech': {
    priority: 'high',
    monitoring: 'daily',
    category: 'iot_tech',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_5g_tech': {
    priority: 'high',
    monitoring: 'daily',
    category: '5g_tech',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_6g_tech': {
    priority: 'high',
    monitoring: 'daily',
    category: '6g_tech',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_wifi_tech': {
    priority: 'high',
    monitoring: 'daily',
    category: 'wifi_tech',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_bluetooth_tech': {
    priority: 'high',
    monitoring: 'daily',
    category: 'bluetooth_tech',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_nfc_tech': {
    priority: 'high',
    monitoring: 'daily',
    category: 'nfc_tech',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_rfid_tech': {
    priority: 'high',
    monitoring: 'daily',
    category: 'rfid_tech',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_lora_tech': {
    priority: 'high',
    monitoring: 'daily',
    category: 'lora_tech',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_sigfox_tech': {
    priority: 'high',
    monitoring: 'daily',
    category: 'sigfox_tech',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_nb_iot_tech': {
    priority: 'high',
    monitoring: 'daily',
    category: 'nb_iot_tech',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_cat_m1_tech': {
    priority: 'high',
    monitoring: 'daily',
    category: 'cat_m1_tech',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_cat_nb1_tech': {
    priority: 'high',
    monitoring: 'daily',
    category: 'cat_nb1_tech',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_cat_m2_tech': {
    priority: 'high',
    monitoring: 'daily',
    category: 'cat_m2_tech',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_cat_m3_tech': {
    priority: 'high',
    monitoring: 'daily',
    category: 'cat_m3_tech',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_cat_m4_tech': {
    priority: 'high',
    monitoring: 'daily',
    category: 'cat_m4_tech',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_cat_m5_tech': {
    priority: 'high',
    monitoring: 'daily',
    category: 'cat_m5_tech',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_cat_m6_tech': {
    priority: 'high',
    monitoring: 'daily',
    category: 'cat_m6_tech',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_cat_m7_tech': {
    priority: 'high',
    monitoring: 'daily',
    category: 'cat_m7_tech',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_cat_m8_tech': {
    priority: 'high',
    monitoring: 'daily',
    category: 'cat_m8_tech',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_cat_m9_tech': {
    priority: 'high',
    monitoring: 'daily',
    category: 'cat_m9_tech',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'eit_cat_m10_tech': {
    priority: 'high',
    monitoring: 'daily',
    category: 'cat_m10_tech',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 10, window: 60000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },

  // MEDIUM PRIORITY - Weekly monitoring (100 sources)
  'umweltfoerderung': {
    priority: 'medium',
    monitoring: 'weekly',
    category: 'environmental',
    enabled: true,
    retryAttempts: 2,
    timeout: 20000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 5, window: 120000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'clean_hydrogen': {
    priority: 'medium',
    monitoring: 'weekly',
    category: 'environmental',
    enabled: true,
    retryAttempts: 2,
    timeout: 20000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 5, window: 120000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'vienna_business_agency': {
    priority: 'medium',
    monitoring: 'weekly',
    category: 'regional_grants',
    enabled: true,
    retryAttempts: 2,
    timeout: 20000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 5, window: 120000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'salzburg_business': {
    priority: 'medium',
    monitoring: 'weekly',
    category: 'regional_grants',
    enabled: true,
    retryAttempts: 2,
    timeout: 20000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 5, window: 120000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'tyrol_business': {
    priority: 'medium',
    monitoring: 'weekly',
    category: 'regional_grants',
    enabled: true,
    retryAttempts: 2,
    timeout: 20000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 5, window: 120000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'styria_business': {
    priority: 'medium',
    monitoring: 'weekly',
    category: 'regional_grants',
    enabled: true,
    retryAttempts: 2,
    timeout: 20000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 5, window: 120000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'upper_austria_business': {
    priority: 'medium',
    monitoring: 'weekly',
    category: 'regional_grants',
    enabled: true,
    retryAttempts: 2,
    timeout: 20000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 5, window: 120000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'lower_austria_business': {
    priority: 'medium',
    monitoring: 'weekly',
    category: 'regional_grants',
    enabled: true,
    retryAttempts: 2,
    timeout: 20000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 5, window: 120000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'carinthia_business': {
    priority: 'medium',
    monitoring: 'weekly',
    category: 'regional_grants',
    enabled: true,
    retryAttempts: 2,
    timeout: 20000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 5, window: 120000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'vorarlberg_business': {
    priority: 'medium',
    monitoring: 'weekly',
    category: 'regional_grants',
    enabled: true,
    retryAttempts: 2,
    timeout: 20000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 5, window: 120000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'burgenland_business': {
    priority: 'medium',
    monitoring: 'weekly',
    category: 'regional_grants',
    enabled: true,
    retryAttempts: 2,
    timeout: 20000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 5, window: 120000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },

  // LOW PRIORITY - Monthly monitoring (50+ sources)
  'small_regional_program_1': {
    priority: 'low',
    monitoring: 'monthly',
    category: 'regional_grants',
    enabled: true,
    retryAttempts: 1,
    timeout: 15000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 1, window: 600000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'small_regional_program_2': {
    priority: 'low',
    monitoring: 'monthly',
    category: 'regional_grants',
    enabled: true,
    retryAttempts: 1,
    timeout: 15000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 1, window: 600000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'niche_program_1': {
    priority: 'low',
    monitoring: 'monthly',
    category: 'specialized',
    enabled: true,
    retryAttempts: 1,
    timeout: 15000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 1, window: 600000 },
    robotsTxt: '',
    respectRobotsTxt: true
  },
  'niche_program_2': {
    priority: 'low',
    monitoring: 'monthly',
    category: 'specialized',
    enabled: true,
    retryAttempts: 1,
    timeout: 15000,
    healthStatus: 'unknown',
    lastChecked: null,
    successRate: 0,
    averageResponseTime: 0,
    errorCount: 0,
    lastError: null,
    rateLimit: { requests: 1, window: 600000 },
    robotsTxt: '',
    respectRobotsTxt: true
  }
};

// Get sources by priority
export function getSourcesByPriority(priority: 'high' | 'medium' | 'low'): string[] {
  return Object.entries(SOURCE_PRIORITIES)
    .filter(([_, config]) => config.priority === priority)
    .map(([sourceId, _]) => sourceId);
}

// Get sources by monitoring frequency
export function getSourcesByMonitoring(monitoring: 'daily' | 'weekly' | 'monthly'): string[] {
  return Object.entries(SOURCE_PRIORITIES)
    .filter(([_, config]) => config.monitoring === monitoring)
    .map(([sourceId, _]) => sourceId);
}

// Get sources by category
export function getSourcesByCategory(category: string): string[] {
  return Object.entries(SOURCE_PRIORITIES)
    .filter(([_, config]) => config.category === category)
    .map(([sourceId, _]) => sourceId);
}

// Get enabled sources
export function getEnabledSources(): string[] {
  return Object.entries(SOURCE_PRIORITIES)
    .filter(([_, config]) => config.enabled)
    .map(([sourceId, _]) => sourceId);
}

// Get source configuration
export function getSourceConfig(sourceId: string): SourcePriority | null {
  return SOURCE_PRIORITIES[sourceId] || null;
}

// Get monitoring schedule
export function getMonitoringSchedule(): { [frequency: string]: string[] } {
  return {
    daily: getSourcesByMonitoring('daily'),
    weekly: getSourcesByMonitoring('weekly'),
    monthly: getSourcesByMonitoring('monthly')
  };
}

// Get category groups
export function getCategoryGroups(): { [category: string]: string[] } {
  const groups: { [category: string]: string[] } = {};
  
  for (const [sourceId, config] of Object.entries(SOURCE_PRIORITIES)) {
    if (!groups[config.category]) {
      groups[config.category] = [];
    }
    groups[config.category].push(sourceId);
  }
  
  return groups;
}
