[build]
  command = "npm install && npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"

# Handle client-side routing for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Handle static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Handle API routes (redirect to 404 for static export)
[[redirects]]
  from = "/api/*"
  to = "/404"
  status = 404
