// Source Register - Top 20 Programs with Data Freshness Tracking
export interface SourceInfo {
  id: string;
  name: string;
  source: string;
  lastChecked: string;
  status: 'active' | 'inactive' | 'deprecated';
  priority: 'high' | 'medium' | 'low';
  programs: number;
  fields: string[];
  monitoring: 'daily' | 'weekly' | 'monthly';
  category: string;
  enabled: boolean;
  retryAttempts: number;
  timeout: number;
}

export const sourceRegister: SourceInfo[] = [
  {
    id: 'aws_at',
    name: 'Austria Wirtschaftsservice (AWS)',
    source: 'https://www.aws.at/',
    lastChecked: '2025-01-15',
    status: 'active',
    priority: 'high',
    programs: 3,
    fields: ['q1_country', 'q2_entity_stage', 'q4_theme', 'q9_team_diversity'],
    monitoring: 'daily',
    category: 'austrian_grants',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000
  },
  {
    id: 'ffg_at',
    name: 'Austrian Research Promotion Agency (FFG)',
    source: 'https://www.ffg.at/',
    lastChecked: '2025-01-15',
    status: 'active',
    priority: 'high',
    programs: 4,
    fields: ['q1_country', 'q6_rnd_in_at', 'q7_collaboration'],
    monitoring: 'daily',
    category: 'research_grants',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000
  },
  {
    id: 'eic_europa',
    name: 'European Innovation Council (EIC)',
    source: 'https://eic.ec.europa.eu/',
    lastChecked: '2025-01-15',
    status: 'active',
    priority: 'high',
    programs: 1,
    fields: ['q1_country', 'q3_company_size', 'q4_theme', 'q8_funding_types'],
    monitoring: 'daily',
    category: 'eu_programs',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000
  },
  {
    id: 'horizon_europe',
    name: 'Horizon Europe Programme',
    source: 'https://ec.europa.eu/info/research-and-innovation/funding/funding-opportunities/funding-programmes-and-open-calls/horizon-europe_en',
    lastChecked: '2025-01-15',
    status: 'active',
    priority: 'high',
    programs: 1,
    fields: ['q1_country', 'q4_theme', 'q6_rnd_in_at'],
    monitoring: 'daily',
    category: 'eu_programs',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000
  },
  {
    id: 'umweltfoerderung',
    name: 'Umweltförderung Betriebe',
    source: 'https://www.umweltfoerderung.at/',
    lastChecked: '2025-01-15',
    status: 'active',
    priority: 'medium',
    programs: 1,
    fields: ['q3_company_size', 'q10_env_benefit'],
    monitoring: 'weekly',
    category: 'environmental',
    enabled: true,
    retryAttempts: 2,
    timeout: 20000
  },
  {
    id: 'clean_hydrogen',
    name: 'Clean Hydrogen Partnership',
    source: 'https://www.clean-hydrogen.europa.eu/',
    lastChecked: '2025-01-15',
    status: 'active',
    priority: 'medium',
    programs: 1,
    fields: ['q10_env_benefit'],
    monitoring: 'weekly',
    category: 'environmental',
    enabled: true,
    retryAttempts: 2,
    timeout: 20000
  },
  {
    id: 'eit_health',
    name: 'EIT Health',
    source: 'https://www.eithealth.eu/',
    lastChecked: '2025-01-15',
    status: 'active',
    priority: 'high',
    programs: 1,
    fields: ['q4_theme', 'q6_rnd_in_at'],
    monitoring: 'daily',
    category: 'health',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000
  },
  {
    id: 'eit_digital',
    name: 'EIT Digital',
    source: 'https://www.eitdigital.eu/',
    lastChecked: '2025-01-15',
    status: 'active',
    priority: 'high',
    programs: 1,
    fields: ['q4_theme', 'q6_rnd_in_at'],
    monitoring: 'daily',
    category: 'digital',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000
  },
  {
    id: 'eit_urban_mobility',
    name: 'EIT Urban Mobility',
    source: 'https://www.eiturbanmobility.eu/',
    lastChecked: '2025-01-15',
    status: 'active',
    priority: 'high',
    programs: 1,
    fields: ['q4_theme', 'q6_rnd_in_at'],
    monitoring: 'daily',
    category: 'mobility',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000
  },
  {
    id: 'eit_food',
    name: 'EIT Food',
    source: 'https://www.eitfood.eu/',
    lastChecked: '2025-01-15',
    status: 'active',
    priority: 'high',
    programs: 1,
    fields: ['q4_theme', 'q6_rnd_in_at'],
    monitoring: 'daily',
    category: 'food',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000
  },
  {
    id: 'eit_manufacturing',
    name: 'EIT Manufacturing',
    source: 'https://www.eitmanufacturing.eu/',
    lastChecked: '2025-01-15',
    status: 'active',
    priority: 'high',
    programs: 1,
    fields: ['q4_theme', 'q6_rnd_in_at'],
    monitoring: 'daily',
    category: 'manufacturing',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000
  },
  {
    id: 'eit_raw_materials',
    name: 'EIT Raw Materials',
    source: 'https://eitrawmaterials.eu/',
    lastChecked: '2025-01-15',
    status: 'active',
    priority: 'high',
    programs: 1,
    fields: ['q4_theme', 'q6_rnd_in_at'],
    monitoring: 'daily',
    category: 'materials',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000
  },
  {
    id: 'eit_climate',
    name: 'EIT Climate',
    source: 'https://www.eitclimate.eu/',
    lastChecked: '2025-01-15',
    status: 'active',
    priority: 'high',
    programs: 1,
    fields: ['q4_theme', 'q6_rnd_in_at'],
    monitoring: 'daily',
    category: 'climate',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000
  },
  {
    id: 'eit_culture_creativity',
    name: 'EIT Culture & Creativity',
    source: 'https://www.eitculturecreativity.eu/',
    lastChecked: '2025-01-15',
    status: 'active',
    priority: 'high',
    programs: 1,
    fields: ['q4_theme', 'q6_rnd_in_at'],
    monitoring: 'daily',
    category: 'culture',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000
  },
  {
    id: 'eit_energy',
    name: 'EIT Energy',
    source: 'https://www.eitenergy.eu/',
    lastChecked: '2025-01-15',
    status: 'active',
    priority: 'high',
    programs: 1,
    fields: ['q4_theme', 'q6_rnd_in_at'],
    monitoring: 'daily',
    category: 'energy',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000
  },
  {
    id: 'eit_water',
    name: 'EIT Water',
    source: 'https://www.eitwater.eu/',
    lastChecked: '2025-01-15',
    status: 'active',
    priority: 'high',
    programs: 1,
    fields: ['q4_theme', 'q6_rnd_in_at'],
    monitoring: 'daily',
    category: 'water',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000
  },
  {
    id: 'wko_at',
    name: 'Austrian Economic Chamber (WKO)',
    source: 'https://www.wko.at/',
    lastChecked: '2025-01-15',
    status: 'active',
    priority: 'high',
    programs: 2,
    fields: ['q1_country', 'q3_company_size', 'q4_theme'],
    monitoring: 'daily',
    category: 'business_grants',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000
  },
  {
    id: 'ams_at',
    name: 'Austrian Employment Service (AMS)',
    source: 'https://www.ams.at/',
    lastChecked: '2025-01-15',
    status: 'active',
    priority: 'high',
    programs: 2,
    fields: ['q1_country', 'q3_company_size', 'q9_team_diversity'],
    monitoring: 'daily',
    category: 'employment',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000
  },
  {
    id: 'oesb_at',
    name: 'ÖSB Consulting',
    source: 'https://www.oesb.at/',
    lastChecked: '2025-01-15',
    status: 'active',
    priority: 'high',
    programs: 1,
    fields: ['q1_country', 'q3_company_size', 'q4_theme'],
    monitoring: 'daily',
    category: 'consulting',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000
  },
  {
    id: 'vba_at',
    name: 'Vienna Business Agency (VBA)',
    source: 'https://www.viennabusinessagency.at/',
    lastChecked: '2025-01-15',
    status: 'active',
    priority: 'high',
    programs: 2,
    fields: ['q1_country', 'q2_entity_stage', 'q4_theme'],
    monitoring: 'daily',
    category: 'regional_grants',
    enabled: true,
    retryAttempts: 3,
    timeout: 30000
  }
];