/**
 * PreviewPanel - Live preview of the business plan
 * Shows formatted preview using react-pdf or similar
 * Based on strategic analysis report recommendations
 */

import React, { useState } from 'react';
import { FileText, Download, Eye, EyeOff } from 'lucide-react';
import { Button } from '@/shared/components/ui/button';

interface PreviewPanelProps {
  plan: any;
  sections: any[];
}

export default function PreviewPanel({ plan, sections }: PreviewPanelProps) {
  const [showPreview, setShowPreview] = useState(true);
  const [previewFormat, setPreviewFormat] = useState<'pdf' | 'docx'>('pdf');

  // For now, show a formatted text preview
  // TODO: Integrate react-pdf for actual PDF rendering
  const renderPreview = () => {
    if (!showPreview) {
      return (
        <div className="flex items-center justify-center h-full text-gray-500">
          <div className="text-center">
            <EyeOff className="h-12 w-12 mx-auto mb-2 text-gray-400" />
            <p className="text-sm">Preview hidden</p>
            <Button
              onClick={() => setShowPreview(true)}
              size="sm"
              variant="outline"
              className="mt-4"
            >
              Show Preview
            </Button>
          </div>
        </div>
      );
    }

    return (
      <div className="space-y-6">
        {/* Document Header */}
        <div className="border-b border-gray-200 pb-4">
          <h1 className="text-2xl font-bold text-gray-900 mb-2">
            {plan?.title || 'Business Plan'}
          </h1>
          {plan?.subtitle && (
            <p className="text-lg text-gray-600">{plan.subtitle}</p>
          )}
          {plan?.author && (
            <p className="text-sm text-gray-500 mt-2">Prepared by: {plan.author}</p>
          )}
          {plan?.date && (
            <p className="text-sm text-gray-500">Date: {plan.date}</p>
          )}
        </div>

        {/* Table of Contents */}
        <div className="border-b border-gray-200 pb-4">
          <h2 className="text-xl font-semibold text-gray-900 mb-3">Table of Contents</h2>
          <ol className="space-y-1 text-sm">
            {sections.map((section, index) => (
              <li key={section.key || index} className="flex items-center gap-2">
                <span className="text-gray-500 w-8">{index + 1}.</span>
                <a
                  href={`#section-${index}`}
                  className="text-blue-600 hover:underline"
                >
                  {section.title}
                </a>
                {section.required && (
                  <span className="text-xs text-red-500">*</span>
                )}
              </li>
            ))}
          </ol>
        </div>

        {/* Sections */}
        <div className="space-y-8">
          {sections.map((section, index) => {
            if (!section.content || section.content.trim().length === 0) {
              return null;
            }

            return (
              <div
                key={section.key || index}
                id={`section-${index}`}
                className="border-b border-gray-200 pb-6 last:border-0"
              >
                <h2 className="text-xl font-semibold text-gray-900 mb-3">
                  {index + 1}. {section.title}
                </h2>
                {section.description && (
                  <p className="text-sm text-gray-600 mb-4 italic">
                    {section.description}
                  </p>
                )}
                <div className="prose prose-sm max-w-none text-gray-700 whitespace-pre-wrap">
                  {section.content}
                </div>
                {section.wordCount && (
                  <p className="text-xs text-gray-500 mt-2">
                    Word count: {section.wordCount}
                    {section.wordCountMin && section.wordCountMax && (
                      <span>
                        {' '}(Target: {section.wordCountMin}-{section.wordCountMax})
                      </span>
                    )}
                  </p>
                )}
              </div>
            );
          })}
        </div>

        {/* Footer */}
        <div className="border-t border-gray-200 pt-4 mt-8">
          <p className="text-xs text-gray-500 text-center">
            Generated by Plan2Fund • {new Date().toLocaleDateString()}
          </p>
        </div>
      </div>
    );
  };

  return (
    <div className="flex flex-col h-full">
      {/* Toolbar */}
      <div className="flex items-center justify-between p-4 border-b border-gray-200">
        <div className="flex items-center gap-2">
          <FileText className="h-5 w-5 text-gray-600" />
          <span className="text-sm font-medium text-gray-900">Preview</span>
        </div>
        <div className="flex items-center gap-2">
          <Button
            onClick={() => setShowPreview(!showPreview)}
            size="sm"
            variant="ghost"
          >
            {showPreview ? (
              <>
                <EyeOff className="h-4 w-4 mr-2" />
                Hide
              </>
            ) : (
              <>
                <Eye className="h-4 w-4 mr-2" />
                Show
              </>
            )}
          </Button>
          <Button
            size="sm"
            variant="outline"
            onClick={() => {
              // TODO: Implement export
              console.log('Export preview as', previewFormat);
            }}
          >
            <Download className="h-4 w-4 mr-2" />
            Export
          </Button>
        </div>
      </div>

      {/* Preview Content */}
      <div className="flex-1 overflow-y-auto p-6 bg-white">
        <div className="max-w-4xl mx-auto bg-white shadow-sm rounded-lg p-8">
          {renderPreview()}
        </div>
      </div>
    </div>
  );
}

