name: Schema & Freshness CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  validate-schema-freshness:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run schema and freshness validation
      run: node scripts/ci-schema-freshness.js
      
    - name: Upload validation results
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: validation-results
        path: |
          scripts/diff-output/
          *.log
          
  source-diff-check:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install GitHub CLI
      run: |
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
        sudo apt update
        sudo apt install gh
        
    - name: Configure Git
      run: |
        git config --global user.name "plan2fund-bot"
        git config --global user.email "bot@plan2fund.ai"
        
    - name: Run source diff fetcher
      run: node scripts/source-diff-fetcher.js
      continue-on-error: true
      
    - name: Upload diff results
      uses: actions/upload-artifact@v4
      with:
        name: source-diff-results
        path: scripts/diff-output/
        
    - name: Run PR automation
      if: success() && steps.source-diff.outcome == 'success'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: |
        # Find the latest diff results file
        LATEST_DIFF_FILE=$(find scripts/diff-output -name "diff-results-*.json" | sort | tail -1)
        
        if [ -f "$LATEST_DIFF_FILE" ]; then
          echo "Running PR automation with $LATEST_DIFF_FILE"
          node scripts/pr-automation.js "$LATEST_DIFF_FILE"
        else
          echo "No diff results file found, skipping PR automation"
        fi
      continue-on-error: true
      
    - name: Comment on PR if created
      if: success() && steps.pr-automation.outcome == 'success'
      run: |
        echo "PR automation completed successfully"
        # Additional PR management can be added here
